# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Github iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'TinyConstraints'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SDWebImageSVGCoder'
  pod 'NVActivityIndicatorView'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  # Pods for Github iOS

end
